# Generated by Django 5.2.8 on 2025-11-18 05:55

from django.db import migrations
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: create_admin_user(apps),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def create_admin_user(apps):
    UserProfile = apps.get_model('rideshare', 'UserProfile')
    User = apps.get_model('auth', 'User')

    # Create admin user if not exists
    if not User.objects.filter(email='jaswanth@gmail.com').exists():
        user = User.objects.create_user(
            username='jaswanth@gmail.com',
            email='jaswanth@gmail.com',
            password='123456',
            first_name='Admin'
        )
        UserProfile.objects.create(user=user, role='admin')
