# Generated by Django 5.2.8 on 2025-11-20 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0004_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rating',
        ),
        migrations.AddField(
            model_name='booking',
            name='cleanliness_rating',
            field=models.IntegerField(blank=True, help_text='Cleanliness rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='driving_smoothness_rating',
            field=models.IntegerField(blank=True, help_text='Driving smoothness rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='legroom_rating',
            field=models.IntegerField(blank=True, help_text='Legroom rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='temperature_comfort_rating',
            field=models.IntegerField(blank=True, help_text='Temperature comfort rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
